### ISSUE TITLE
SDDM crashed with a core dump

### ISSUE THREAD

**Issue by galaxy001** [vetzki/nvidia-prime-switch-sddm#3]
Under Manjaro KDE 18.0, with Thinkpad P52.
I find the SDDM crashed with a core dump after switched to *nvidia* and rebooted.
Switching to *intel* works fine.

**Comment by vetzki** [comment]
Do you use the current nvidia 396 pakckage or the 390xx one ? 

Which kernel version do you use?

Can you try another kernel version?

Does the crash also occur on lightdm or nodm package ?

Do you use any acpi_osi  value in cmdline?

**Comment by galaxy001** [comment]
linux419-nvidia 1:415.18-3
No acpi_osi set.

I'll try others later.

**Comment by vetzki** [comment]
Please try other kernel versions (maybe 414) and/or try acpi_osi=Linux in cmdline (although probably wont help but worth a try)

**Comment by vetzki** [comment]
I didn't encounter any issue when using sddm. (I also didn't get any response to the latest reply)

So I'm closing the issue.

If you still have troubles, try another kernel version and check if everything is up-to-date. Should this not fix your issue, please open a new one (or re-open this one if possible)
